project:
  type: website

website:
  title: "Poppy J Hesketh Best, Ph.D"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - blog.qmd
      - publications.qmd
      - projects.qmd
      - anatomy-of-a-bash.qmd

format:
  html:
    theme:
      - cosmo
      - brand
    css: styles.css
    toc: true



