project:
  type: website

website:
  title: "Poppy J Hesketh Best, Ph.D"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - publications.qmd
      - projects.qmd
      - href: blog/index.qmd
        text: Blog
      - href: anatomy-of-a-bash/index.qmd
        text: Anatomy of a Bash
        
format:
  html:
    theme:
      - cosmo
      - brand
    css: styles.css
    toc: true



