project:
  type: website

website:
  title: "Poppy J Hesketh Best, Ph.D"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - href: projects.qmd
        text: Projects
      - href: publications.qmd
        text: Publications
#      - href: SciComms.qmd
#        text: SciComms
      - href: https://github.com/pjhesbest
        text: GitHub
      - href: https://bsky.app/profile/pjhesbes.bsky.social
        text: BlueSky
  favicon: "logo.png"
  twitter-card: true
  site-url: "https://example.com"

format:
  html:
    css: styles.css
    toc: true

remote_theme: pages-themes/minimal@v0.2.0
plugins:
- jekyll-remote-theme
