project:
  type: website

website:
  title: "Poppy J Hesketh Best, Ph.D"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - projects.qmd
      - publications.qmd
      - SciComms.qmd
      #- CV.qmd

format:
  html:
    theme:
      - solarized
    css: styles.css
    toc: true