---
title: "Publications"
format:
    html:
     meta:
        keywords: "Microbiology, Bioinformatics, Genomics, Metagenomics, Microbiomes, Viromes"
---

<u>[ResearchGate](https://www.researchgate.net/profile/Poppy-Hesketh-Best):</u> **125.4** Research Interest Score || **55** Citations || **5** h-index

<u>[GoogleScholar](https://scholar.google.com/citations?user=vwuYwIMAAAAJ&hl=en):</u> **55** Citations || **5** h-index || **2** i10-index

***

### 2025

McKeown D., *et al*, , Schroeder D.C. (*in review*) "Virome compositions indicate that viral spillover is a dead-end between western honey bee and the common eastern bumblebee"

<span class="keyword-box">Honey bees</span>
<span class="keyword-box">Nanopore sequencing</span>
<span class="keyword-box">RNA viromes</span>
<span class="keyword-box">Metagenomics</span>
<span class="keyword-box">Environmental Microbiology</span>

Chrismas N.A., *et al.*, Cunliffe M. (*accepted*) "Evolutionary and biological mechanisms underpinning chitin degradation in aquatic fungi"

<span class="keyword-box">Aquatic fungi</span>
<span class="keyword-box">Chytrids</span>
<span class="keyword-box">Environmental Microbiology</span>
<span class="keyword-box">Marine Microbiology</span>

### 2024

**Hesketh-Best P.J.**, *et al.*, Schroeder D.C. (2024) “Nationwide survey of honey bee viruses in the United States of America reveals shifts in dominant Deformed wing virus variants”. *Comms. Bio.* doi: [https://doi.org/10.1038/s42003-024-07333-9](https://doi.org/10.1038/s42003-024-07333-9)

<span class="keyword-box">Honey bees</span>
<span class="keyword-box">Nanopore sequencing</span>
<span class="keyword-box">RNA viromes</span>
<span class="keyword-box">Metagenomics</span>
<span class="keyword-box">Environmental Microbiology</span>

**Hesketh-Best P.J**, *et al.*, Schroeder D.C. (2024) “Sacbrood viruses and select Lake Sinai virus variants dominated *Apis mellifera* colonies symptomatic for European foulbrood”. *Microbiol. Spectr. ASM* doi: [https://doi.org/10.1128/spectrum.00656-24](https://doi.org/10.1128/spectrum.00656-24)

<span class="keyword-box">Honey bees</span>
<span class="keyword-box">Nanopore sequencing</span>
<span class="keyword-box">RNA viromes</span>
<span class="keyword-box">Metagenomics</span>
<span class="keyword-box">Environmental Microbiology</span>

Wallace B., *et al.*, **Hesketh-Best P.J.**, Silveira C.B. (2024) “Globally distributed bacteriophage genomes reveal mechanisms of tripartite phage-bacteria-coral interactions” *ISME J.* doi: [https://doi.org/10.1093/ismejo/wrae132](https://doi.org/10.1093/ismejo/wrae132)

<span class="keyword-box">Bacteriophages</span>
<span class="keyword-box">Virus-Host dyanmics</span>
<span class="keyword-box">Metagenomics</span>
<span class="keyword-box">Viromes</span>
<span class="keyword-box">Marine Microbiology</span>

Stiffler A., **Hesketh-Best P.J.**, *et al.*, Silveira C.B. (2024) “Genomic and induction evidence for bacteriophage contributions to sargassum-bacteria symbioses” *BMC Microbiome* doi: [https://doi.org/10.1186/s40168-024-01860-7](https://doi.org/10.1186/s40168-024-01860-7)

<span class="keyword-box">Bacteriophages</span>
<span class="keyword-box">Virus-Host dyanmics</span>
<span class="keyword-box">Metagenomics</span>
<span class="keyword-box">Viromes</span>
<span class="keyword-box">Marine Microbiology</span>

Varona N.S, **Hesketh-Best P.J.**, *et al.*, Silveira C.B. (2024) ‘Host-specific viral predation network on coral reefs’ ISME Journal doi: [https://doi.org/10.1093/ismejo/wrae240](https://doi.org/10.1093/ismejo/wrae240)

<span class="keyword-box">Bacteriophages</span>
<span class="keyword-box">Proximility-ligation sequencing</span>
<span class="keyword-box">Virus-Host dyanmics</span>
<span class="keyword-box">Metagenomics</span>
<span class="keyword-box">Viromes</span>
<span class="keyword-box">Marine Microbiology</span>

Nikulin S.L., **Hesketh-Best P.J.**, *et al.*, Schroeder C.D. (2024) ‘A semi-automated and high-throughput approach for the detection of honey bee viruses in bee samples’. *PLoS ONE* doi: [https://doi.org/10.1371/journal.pone.0297623](https://doi.org/10.1371/journal.pone.0297623)

<span class="keyword-box">Honey bees</span>
<span class="keyword-box">Nanopore sequencing</span>
<span class="keyword-box">RNA viromes</span>
<span class="keyword-box">Metagenomics</span>
<span class="keyword-box">Experimental Microbiology</span>

### 2023

**Hesketh-Best P.J.**, *et al.*, Silveira C.B. (2023) ‘Viruses of sulfur oxidizing phototrophs encode genes for pigment, carbon, and sulfur metabolisms’. Communications Earth & Enviroment doi: [https://doi.org/10.1038/s43247-023-00796-4](https://doi.org/10.1038/s43247-023-00796-4)

<span class="keyword-box">Bacteriophages</span>
<span class="keyword-box">Nanopore sequencing</span>
<span class="keyword-box">DNA viromes</span>
<span class="keyword-box">Metagenomics</span>
<span class="keyword-box">Environmental Microbiology</span>
<span class="keyword-box">Auxilllary metabolic genes</span>

**Hesketh-Best P.J.**, *et al.*, Upton M. (2023) ‘Whole genomes of deep-sea sponge-associated bacteria exhibit high novel natural product potential’. *FEMS Microbe* doi: [https://doi.org/10.1093/femsmc/xtad005](https://doi.org/10.1093/femsmc/xtad005)

<span class="keyword-box">Deep sea sponges</span>
<span class="keyword-box">Whole-genome sequencing</span>
<span class="keyword-box">Antibiotic discovery</span>
<span class="keyword-box">Marine Microbiology</span>

### 2021

Koch M.J., **Hesketh-Best P.J.**, *et al.*, Upton M. (2021) ‘Impact of growth media and pressure on the diversity and antimicrobial activity of isolates from two species of Hexactinellid Sponge’. *Microbiology Journal* doi: [https://doi.org/10.1099/mic.0.001123](https://doi.org/10.1099/mic.0.001123)

<span class="keyword-box">Deep sea sponges</span>
<span class="keyword-box">Antibiotic discovery</span>
<span class="keyword-box">Marine Microbiology</span>

**Hesketh-Best P.J.**, Mouritzen M.V., *et al.*, Upton M. (2021) ‘*Galleria mellonella* exhibit a weight-dependent lethal median dose against Methicillin-resistant Staphylococcus aureus’. *Pathogens and Disease (FEMS)*. doi: [https://doi.org/10.1093/femspd/ftab003a](https://doi.org/10.1093/femspd/ftab003a)

<span class="keyword-box">Galleria mellonella</span>
<span class="keyword-box">Antibiotic testing</span>
<span class="keyword-box">Experimental Microbiology</span>